name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Perform unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: main
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: |
          npm install
      - name: Test using Jest
        run: |
          npm run test

